### ISSUE TITLE
Cannot play sound effects

### ISSUE THREAD

**Issue by hlabrand** [vorple/inform6#11]
(reported by Thomas Bøvith)
In "Serinette", >wind key doesn't play anything, and the web console says

"HTTP load failed with status 404. Load of media resource folder/vorple.options.resource_paths.audio+%27/winding.mp3%27 failed."

This is because the code for sound effects is
     BuildCommand("$('<audio class=@@92'vorple-audio vorple-sound@@92' src=vorple.options.resource_paths.audio+@@92'/", VorpleEscape(file), "@@92' autoplay loop>').appendTo('body')")

The ' within ' has to be escaped using \, but apparently doing so prevents concatenation? It works fine for music, though, but this is different :
   BuildCommand("vorple.audio.playMusic(vorple.options.resource_paths.audio+'/", VorpleEscape(file), "', true)")

I don't really know how to fix it, if somebody knows more about JS than I do...

**Comment by thomasboevith** [comment]
This version of VorplePlaySoundEffect should fix this issue:

```
[ VorplePlaySoundEffect file loop;
    if (loop == LOOP_SOUND) {
        ! @@92 = backslash
         VorpleExecuteJavaScriptCommand(BuildCommand("$('<audio class=@@92'vorple-audio vorple-sound@@92' src='+vorple.options.resource_paths.audio+'/", VorpleEscape(file), " autoplay loop>').appendTo('body')"));
    } else {
         VorpleExecuteJavaScriptCommand(BuildCommand("$('<audio class=@@92'vorple-audio vorple-sound@@92' src='+vorple.options.resource_paths.audio+'/", VorpleEscape(file), " autoplay>').appendTo('body')"));
    }
];
```

**Comment by hlabrand** [comment]
Thanks Thomas! The code works and has been committed :)
