### ISSUE TITLE
Cyrillic characters in the webpage's title

### ISSUE THREAD

**Issue by cheshiren** [vorple/inform6#22]
Hi.

I'm getting "????" instead of "Сквот" in the title of a vorple's web-interpreter. First, it reads "Vorple" at the loading phase and then changes to question marks. Couldn't find where it is handled in the code.

**Comment by hlabrand** [comment]
Hi, I will look at it in the next few days. It's on line 225 of the vorple.h file, itself calling the function on line 527, which is supposed to call Unicode function on line 506. I will investigate.

(Of course, the usual caveats, but you made sure you compiled with the -Cu flag? And your source is indeed in UTF-8 ?)

**Comment by cheshiren** [comment]
> (Of course, the usual caveats, but you made sure you compiled with the -Cu flag? And your source is indeed in UTF-8 ?)

Yep. Everything is as it should be.

**Comment by hlabrand** [comment]
Ok, I found the problem I think. The "bp_output_stream" function uses "glk_stream_open_memory", which writes to a byte array, when it should be using "glk_stream_open_memory_uni", which writes to a word array. (This is line 117 of vorple.h.)

The problem is, if I switch that, there are a bunch more errors (booleans aren't recognized, gluing strings together doesn't work anymore, etc.). I probably need to go through the Glulx spec and the vorple.h code and see if there are other functions to change, or even change all the array types... I will figure it out eventually but this is not a one-line fix. Sorry!

**Comment by hlabrand** [comment]
(If I change line 355 to put_buffer_stream_uni, this fails the Vorple handshake ; I similarly tried to replace all the calls to functions that had "_uni" equivalents (lines 101, 117, 140, 301, 340, 355, 357, 612, 635), and this passed the vorple handshake but broke a bunch of other stuff. I'll keep looking...)

**Comment by cheshiren** [comment]
Well, thanks for your efforts anyway. Does this relate to the webpage's title only or I should expect problems in some other places?

**Comment by hlabrand** [comment]
There will be problems in other places, basically any Javascript command with variable text... This is why it's important for me to fix it soon. Zarf [helped me to figure out](https://intfiction.org/t/i6-adapting-glulx-code-to-handle-unicode/42011/2) how to solve the problem, it's just a bit of work. I hope to do it in the next couple of weeks, remind me if I don't give more news soon...

**Comment by cheshiren** [comment]
Hi! Is there any news on the topic?

**Comment by juhana** [comment]
I have time set aside for this next week, I'm not an I6 expert but because the I7 version works correctly I should be able to get some insight from the I6 code that I7 generates.

**Comment by hlabrand** [comment]
I'm sorry I couldn't find the time; I sent the resources and intermediate code to Juhana in the hopes it helps him to figure it out. I feel like there's a number of changes to do all at the same time before it can work, so it's a tricky issue. I'm sure we'll manage to fix it though! Thanks for your patience.

**Comment by juhana** [comment]
The issue has now been fixed and will be included in the next release, which ships next weekend. You can also download https://raw.githubusercontent.com/vorple/inform6/master/vorple.h now which contains the fix.
