### ISSUE TITLE
Can't get to prompt in Cyrillic games

### ISSUE THREAD

**Issue by cheshiren** [vorple/inform6#26]
Hi!
I have problems with the new release - none of Cyrillic-based games can get past intro texts and to the prompt.
I tested this bunch of Russian glulx demos: [https://yadi.sk/d/fUI9izYMDFcmpQ](url) and none of them worked.
Not sure if it would help but the title of webpage read "Game - undefined" in all cases.

**Comment by cheshiren** [comment]
More info: in my Vorple-oriented game I can't get past emblazon and have fatal-error: "Quixe init: ReferenceError: unicode_lower_table is not defined unicode_lower_table is not defined ReferenceError".
![image](https://user-images.githubusercontent.com/666765/68103120-5ea8aa80-fef7-11e9-88ba-549e36bb5a3d.png)

**Comment by hlabrand** [comment]
Hi! I will take a look at this this weekend. Thank you!

Le 03/11/2019 à 23:37, Vyacheslav Dobranov a écrit :
> More info: in my Vorple-oriented game I can't get past emblazon and have fatal-error: "Quixe init: ReferenceError: unicode_lower_table is not defined unicode_lower_table is not defined ReferenceError".
> ![image](https://user-images.githubusercontent.com/666765/68103120-5ea8aa80-fef7-11e9-88ba-549e36bb5a3d.png)
> 
>

**Comment by juhana** [comment]
This looks like an interpreter error, I'm planning to check other issues with it as well this weekend so I can handle this one as well.

**Comment by cheshiren** [comment]
It can be on the Quixe's side indeed: https://github.com/erkyrath/quixe/issues/42

**Comment by juhana** [comment]
@cheshiren Can you try if this version fixes the problem: https://vorple-if.com/tmp/vorple.min.js (right-click --> download file, copy it over the old file)

**Comment by cheshiren** [comment]
> @cheshiren Can you try if this version fixes the problem: https://vorple-if.com/tmp/vorple.min.js (right-click --> download file, copy it over the old file)

Actually, it solved the problem with ReferenceError from the screenshot above (cool!), but I can't get the prompt still:
![image](https://user-images.githubusercontent.com/666765/68594133-b8d9da80-04b8-11ea-8a79-ec8455654b1c.png)
![image](https://user-images.githubusercontent.com/666765/68594169-c55e3300-04b8-11ea-9da2-97969f1d94b2.png)

**Comment by juhana** [comment]
This is now fixed in the new 3.2.1 release: https://vorple-if.com/download.html
